services:
  node:
    build:
      context: .
      dockerfile: ./infra/local/node/Dockerfile
    container_name: nextjs-fargate-node
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

  postgres:
    container_name: nextjs-fargate-db
    image: postgres:17.0
    ports:
      - 5433:5432
    volumes:
      - ./infra/local/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
